"""
Django settings for nluis project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import datetime
import os
from pathlib import Path
from decouple import config, Config, RepositoryEnv

# DOTENV_FILE = '/opt/envs/project-name/.env'
# env_config = Config(RepositoryEnv(DOTENV_FILE))

# use the Config().get() method as you normally would since
# decouple.config uses that internally.
# i.e. config('SECRET_KEY') = env_config.get('SECRET_KEY')
# SECRET_KEY = config('SECRET_KEY')
# SECRET_KEY = env_config.get('SECRET_KEY')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
from nluis.jazz import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS
from nluis.jwt import SIMPLE_JWT

CELERY_BROKER_URL = 'amqp://localhost'

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 'django-insecure-ow*j!4%#noci5nk1t^w*tjkg8f-b5q(m*ty%qomx2-(1mk)hao'
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config('DEBUG', cast=bool)
DEBUG = True

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['nluis.nlupc.go.tz',
                 '127.0.0.1', 'localhost', '144.91.125.106', '192.168.1.135', 'ardhi.info.tz', 'www.ardhi.info.tz']

# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_admin_json_editor',
    'django_json_widget',
    # third party apps
    'coreapi',
    'drf_yasg',
    'decouple',
    'import_export',
    'colorfield',
    'jazzmin',
    # 'silk',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'corsheaders',
    # local apps
    'account',
    'nluis_authorization',
    'nluis_projects',
    'nluis_collect',
    'nluis_localities',
    'nluis_setups',
    'nluis_reports',
    'nluis_spatial',
    'nluis_billing',
    'organization',
    'nluis_form_management',
    'nluis_ccro',
    'nluis_zoning',
]

BASE_URL = 'http://144.91.125.106:8000/'  # Replace with your actual base URL

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'silk.middleware.SilkyMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# X-FRAME OPTIONS HTTP HEADER FOR CLICKJACKING PREVENTION
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'nluis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nluis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        # 'OPTIONS': {
        #     'options': '-c search_path=tx_maker'
        # },
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASS'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', cast=int),
        'TEST': {
            'NAME': 'test_nluis',
        }
    }

}

# EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_USE_SSL = config('EMAIL_USE_SSL')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# auth model
AUTH_USER_MODEL = 'account.User'
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static/'),)

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

UPLOADS_ROOT = os.path.join(BASE_DIR, "data/nluis/downloads/")
DOCS_OUTPUT = os.path.join(BASE_DIR, "data/nluis/downloads/output/")
HTML_TEMPLATE_DIR = os.path.join(BASE_DIR, "data/nluis/documents/doc/html/")

REPORT_PDF_DIR = os.path.join(BASE_DIR, 'files')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # 'EXCEPTION_HANDLER': 'udsmvoting.custom_exception_handler.custom_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 50
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'NLUIS API',
    'DESCRIPTION': 'National Land Use Information System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}


CORS_ALLOWED_ORIGINS = [
    'https://localhost:3000',
    # 'http://192.168.248.14:3000',
    # 'https://192.168.248.14:3000',
    # 'http://154.118.227.140',
    'https://nluis.nlupc.go.tz',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://144.91.125.106:8000',
    'http://144.91.125.106',
    'http://144.91.125.106:3000',
    'http://ardhi.info.tz',
    'https://ardhi.info.tz'
]

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "accept",
    "origin",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        "Auth Token eg [Bearer (JWT)]": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}

BILL_DATE_INPUT_FORMATS = '%Y-%m-%dT%H:%M:%S'
ENGINE_SERVER_IP = config('ENGINE_SERVER_IP')
SP_CODE = config('SP_CODE')
SUB_SP = config('SUB_SP')
SYSTEM_ID = config('SYSTEM_ID')
GEPG_PRIVATE_KEY_FILE = config('GEPG_PRIVATE_KEY_FILE')
GEPG_PRIVATE_KEY_PASS = config('GEPG_PRIVATE_KEY_PASS')
GEPG_PUBLIC_KEY_FILE = config('GEPG_PUBLIC_KEY_FILE')
GEPG_PUBLIC_KEY_PASS = config('GEPG_PUBLIC_KEY_PASS')
NLUIS_PUBLIC_KEY_FILE = config('NLUIS_PUBLIC_KEY_FILE')
NLUIS_PUBLIC_KEY_PASS = config('NLUIS_PUBLIC_KEY_PASS')

# HSTS HEADERS
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
